name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    steps:
    - name: reset
      run: |
      ls
      git init
      git rm -r --cached .
      rm -rf .gitignore
    steps:
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.PAGES }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
